### ISSUE TITLE
ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by Xuhenying** [VoltaicHQ/Progress-Sheet-Updater#25]
After I chose my google account, The Progress Sheet Updater crashed. I got this error: ValueError: check_hostname requires server_hostname from debug.

**Comment by Xuhenying** [comment]
2021-10-15 11:17:55,753 | DEBUG | root | {
  "stats_path": "C:/Users/xuwjf/Desktop/ShadowsocksR-win-4.9.2",
  "sheet_id": "1r2Lh21Rq_BV6WCPN3DojkTGKkL8RwCtrtjC28V1y0-w",
  "scenario_name_ranges": [
    "Intermediate Requirements!E3:E20",
    "Advanced Requirements!E3:E20"
  ],
  "highscore_ranges": [
    "Intermediate Requirements!G3:G20",
    "Advanced Requirements!G3:G20"
  ],
  "average_ranges": [
    "Intermediate Requirements!M3:M20",
    "Advanced Requirements!M3:M20"
  ],
  "run_mode": "watchdog",
  "calculate_averages": true,
  "num_of_runs_to_average": 5,
  "polling_interval": 60,
  "open_config": true
}
2021-10-15 11:17:55,753 | DEBUG | root | Creating service...
2021-10-15 11:19:46,843 | ERROR | root | Uncaught exception
Traceback (most recent call last):
  File "main.py", line 242, in <module>
  File "sheets.py", line 81, in create_service
  File "google_auth_oauthlib\flow.py", line 474, in run_local_server
  File "google_auth_oauthlib\flow.py", line 288, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 344, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 516, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 506, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 827, in _create
ValueError: check_hostname requires server_hostname

**Comment by Xuhenying** [comment]
> Hello, this is quite a rare problem that I have not seen much. You can try following some of the steps in this thread https://stackoverflow.com/questions/67297278/valueerror-check-hostname-requires-server-hostname

Thanks a lot.
But I think I still can't solve this problem. Because I'm using proxy software to connect to my google account.
Do you have any ideas? Thanks again.

**Comment by Y0ndaime** [comment]
No if that is the case I do not think you can solve this error. I am sorry.
