### ISSUE TITLE
How can I use a proxy to connect to googleAPI?

### ISSUE THREAD

**Issue by yobome** [VoltaicHQ/Progress-Sheet-Updater#37]
My network env needs a proxy to connect google API, how can I add a proxy to ProgressSheetUpdater.exe?

```log
2023-09-11 11:02:13,006 | CRITICAL | root | Uncaught exception
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 499, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 347, in <module>
  File "sheets.py", line 81, in create_service
  File "google_auth_oauthlib\flow.py", line 474, in run_local_server
  File "google_auth_oauthlib\flow.py", line 288, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 336, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 515, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

```

**Comment by Y0ndaime** [comment]
Hi, I dont know if you are able to do this with a private google api key. Im sorry but I can't help with that
