### ISSUE TITLE
sqlite3.OperationalError: no such table: TaskData

### ISSUE THREAD

**Issue by uzeboster** [VoltaicHQ/Progress-Sheet-Updater#45]
2024-03-06 18:19:30,276 | DEBUG | root | Creating service...
2024-03-06 18:19:31,385 | DEBUG | root | Game: Aimlab
2024-03-06 18:19:31,385 | DEBUG | root | Initializing scenario data...
2024-03-06 18:19:36,703 | DEBUG | root | Initializing CsLevelIds...
2024-03-06 18:19:37,146 | CRITICAL | root | Uncaught exception
Traceback (most recent call last):
  File "main.py", line 356, in <module>
  File "main.py", line 143, in update_aimlab
sqlite3.OperationalError: no such table: TaskData

**Comment by famousfive1** [comment]
I am also facing the same issue. Any updates on this?

**Comment by famousfive1** [comment]
After some digging, it turns out that the location of the data has changed. It is no longer `LocalLow\statespace\aimlab_tb\klutch.bytes`. Instead, the data is at `LocalLow\statespace\aimlab_tb\Users\ < User ID > \LocalDB\Klutch.bytes`.

After changing this in the conf.py file and building it, it is working fine now and is updating the scores on the sheet. I am unsure if everyone is facing this issue or if only some people have had this data location change. We can have a temporary fix to this by basically asking the user to input the data location in the GUI / config file instead of hard coding it.

Also while building, pip had some trouble installing pyinstaller version 4.1. But using the latest version of the package seemed to work fine. Maybe update it?

**Comment by Y0ndaime** [comment]
Interesting, I will add a way to input the path to the aimlab db soon once I have the time

**Comment by Alexander3a** [comment]
> After some digging, it turns out that the location of the data has changed. It is no longer `LocalLow\statespace\aimlab_tb\klutch.bytes`. Instead, the data is at `LocalLow\statespace\aimlab_tb\Users\ < User ID > \LocalDB\Klutch.bytes`.
> 
> After changing this in the conf.py file and building it, it is working fine now and is updating the scores on the sheet. I am unsure if everyone is facing this issue or if only some people have had this data location change. We can have a temporary fix to this by basically asking the user to input the data location in the GUI / config file instead of hard coding it.
> 
> Also while building, pip had some trouble installing pyinstaller version 4.1. But using the latest version of the package seemed to work fine. Maybe update it?

also have the same problem and this fixed is so can confirm its not just for you facing this issue
